// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig } from 'prisma/config';

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    // Migrations + the default PrismaClient connection both read this.
    // Prefer DIRECT_URL when present (Supabase: port 5432, no PgBouncer)
    // because Prisma migrations create prepared statements that
    // transaction-mode poolers reject. Fall back to DATABASE_URL for
    // setups that have only one URL (Neon, local docker, etc).
    url: process.env['DIRECT_URL'] ?? process.env['DATABASE_URL'],
  },
});
